apiVersion: v1
kind: Service
metadata:
  name: alfred-api
  namespace: alfred
spec:
  selector:
    app: alfred-api
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP
