apiVersion: v1
kind: Service
metadata:
  name: {{ include "alfred.fullname" . }}-redis
  labels:
    app.kubernetes.io/name: {{ include "alfred.name" . }}-redis
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  ports:
    - port: {{ .Values.redis.service.port }}
      targetPort: {{ .Values.redis.service.port }}
      protocol: TCP
      name: redis
  selector:
    app.kubernetes.io/name: {{ include "alfred.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "alfred.fullname" . }}-redis
  labels:
    app.kubernetes.io/name: {{ include "alfred.name" . }}-redis
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "alfred.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "alfred.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: redis
          image: "{{ .Values.redis.image.repository }}:{{ .Values.redis.image.tag }}"
          ports:
            - containerPort: {{ .Values.redis.service.port }}
          resources: {}
